<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('application_checklists', function (Blueprint $table) {
            $table->id();
            $table->unsignedBigInteger('user_id');
            $table->string('transaction_number')->nullable();
            $table->string('name');
            $table->text('positionTitle');
            $table->text('SG_STEP');
            $table->text('MonthlyCompensation');
            $table->text('Daily_Compensation_Casual');
            $table->text('EduText');
            $table->string('education')->nullable()->default('');
            $table->string('education_remarks')->nullable()->default('');
            $table->text('ExpText')->nullable()->default('');
            $table->string('experience')->nullable()->default('');
            $table->text('experience_remarks')->nullable()->default('');
            $table->string('TrainText')->nullable();
            $table->string('training')->nullable();
            $table->text('training_remarks')->nullable();
            $table->string('eligibility_Text')->nullable();
            $table->string('eligibility')->nullable();
            $table->text('eligibility_remarks')->nullable();
            $table->string('Other_Requirements')->nullable();
            $table->text('Other_Requirements_remarks')->nullable();
            $table->string('Senior_HS')->nullable();
            $table->text('Senior_HS_remarks')->nullable();
            $table->string('Common_Requirements')->nullable();
            $table->text('Common_Requirements_remarks')->nullable();
            $table->string('CS_form_no_33_a')->nullable();
            $table->text('CS_form_no_33_a_remarks')->nullable();
            $table->string('CS_form_no_33_b')->nullable();
            $table->text('CS_form_no_33_b_remarks')->nullable();
            $table->string('CS_form_no_34_a')->nullable();
            $table->text('CS_form_no_34_a_remarks')->nullable();
            $table->string('CS_form_no_34_b')->nullable();
            $table->text('CS_form_no_34_b_remarks')->nullable();
            $table->string('CS_form_no_34_c')->nullable();
            $table->text('CS_form_no_34_c_remarks')->nullable();
            $table->string('CS_form_no_34_d')->nullable();
            $table->text('CS_form_no_34_d_remarks')->nullable();
            $table->string('CS_form_no_34_e')->nullable();
            $table->text('CS_form_no_34_e_remarks')->nullable();
            $table->string('CS_form_no_34_f')->nullable();
            $table->text('CS_form_no_34_f_remarks')->nullable();
            $table->string('Employment_Status')->nullable();
            $table->text('Employment_Status_remarks')->nullable();
            $table->string('Provisional_Appointment')->nullable();
            $table->text('Provisional_Appointment_remarks')->nullable();
            $table->string('appointee_subject')->nullable();
            $table->text('appointee_subject_remarks')->nullable();
            $table->string('Nature_of_Appointment')->nullable();
            $table->text('Nature_of_Appointment_remarks')->nullable();
            $table->string('Signature_of_Appointing')->nullable();
            $table->text('Signature_of_Appointing_remarks')->nullable();
            $table->string('Date_of_Signing')->nullable();
            $table->text('Date_of_Signing_remarks')->nullable();
            $table->string('Certification_of_Publication')->nullable();
            $table->text('Certification_of_Publication_remarks')->nullable();
            $table->string('Certification_by_Chairperson')->nullable();
            $table->text('Certification_by_Chairperson_remarks')->nullable();
            $table->string('Acknowledgement_Original')->nullable();
            $table->text('Acknowledgement_Original_remarks')->nullable();
            $table->string('Personal_Data_Sheet')->nullable();
            $table->text('Personal_Data_Sheet_remarks')->nullable();
            $table->string('Is_the_agency_accredited')->nullable();
            $table->text('Is_the_agency_accredited_remarks')->nullable();
            $table->string('If_NOT_accredited')->nullable();
            $table->text('If_NOT_accredited_remarks')->nullable();
            $table->string('Erasures_or_alteration')->nullable();
            $table->text('Erasures_or_alterations_remarks')->nullable();
            $table->string('With_decided_administrative')->nullable();
            $table->text('With_decided_administrative_remarks')->nullable();
            $table->string('Discrepancy_in_name')->nullable();
            $table->text('Discrepancy_in_name_remarks')->nullable();
            $table->string('Change_of_Civil_Status')->nullable();
            $table->text('Change_of_Civil_Status_remarks')->nullable();
            $table->string('Annulment_or_Declaration')->nullable();
            $table->text('Annulment_or_Declaration_remarks')->nullable();
            $table->string('Appointments_issued_by_the_SUCs')->nullable();
            $table->text('Appointments_issued_by_the_SUCs_remarks')->nullable();
            $table->string('Appointment_issued_for_faculty_positions')->nullable();
            $table->text('Appointment_issued_for_faculty_positions_remarks')->nullable();
            $table->string('Appointments_Requiring_Board_Resolution')->nullable();
            $table->text('Appointments_Requiring_Board_Resolution_remarks')->nullable();
            $table->string('Ban_on_Issuance')->nullable();
            $table->text('Ban_on_Issuance_remarks')->nullable();
            $table->string('Certification_issued_by_the_appointing_officer')->nullable();
            $table->text('Certification_issued_by_the_appointing_officer_remarks')->nullable();
            $table->string('Certification_issued_by_the_Provincial')->nullable();
            $table->string('Appointment_to_head_of_department')->nullable();
            $table->string('Concurred')->nullable();
            $table->string('Not_Concurred')->nullable();
            $table->string('Creation_and_reclassification')->nullable();
            $table->string('Non_Disciplinary_in_Nature')->nullable();
            $table->text('Non_Disciplinary_in_Nature_remarks')->nullable();
            $table->string('Certification_issued_by_the_agency')->nullable();
            $table->string('Written_consent_by_the_employee')->nullable();
            $table->string('Temporary_and_Provisional_Appointment')->nullable();
            $table->text('Temporary_and_Provisional_Appointment_remarks')->nullable();
            $table->string('Reclassification')->nullable();
            $table->text('Reclassification_remarks')->nullable();
            $table->string('OR_COPY_AUT_CERT_OF_ELIG')->nullable();
            $table->text('OR_COPY_AUT_CERT_OF_ELIG_remarks')->nullable();
            $table->string('Position_Description_Form')->nullable();
            $table->text('Position_Description_Form_remarks')->nullable();
            $table->string('Oath_of_Office')->nullable();
            $table->text('Oath_of_Office_remarks')->nullable();
            $table->string('Certification_of_Assumption_to_Duty')->nullable();
            $table->text('Certification_of_Assumption_to_Duty_remarks')->nullable();
            $table->string('Performance_Rating')->nullable();
            $table->text('Performance_Rating_remarks')->nullable();
            $table->string('Justification')->nullable();
            $table->text('Justification_remarks')->nullable();
            $table->string('Electronic_file_stored')->nullable();
            $table->text('Electronic_file_stored_remarks')->nullable();
            $table->string('Others')->nullable();
            $table->text('Others_remarks')->nullable();
            $table->timestamps();
            $table->softDeletes();
            $table->foreign('user_id')->references('id')->on('users')->onDelete('cascade');
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('application_checklists');
    }
};
